# 원격 테마 설정 (Minimal Mistakes + dirt 스킨)
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"

# 사이트 기본 메타데이터
title: "Chanwoo Park"
description: "따뜻한 베이지 톤 블로그"

# 사용할 Jekyll 플러그인
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# 사이드바에 표시할 author 정보
author:
  name: "Chanwoo Park"
  avatar: "/assets/images/me.jpg"
  bio: "Undergraduate Software Engineering Student"

# (필요시 추가 설정)
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/
