name: Build and Deploy Jekyll site

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site with Jekyll
        run: bundle exec jekyll build --destination _site

      - name: Upload artifact for Pages
        # ← 여기만 v1 → v3 로 올립니다.
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://seriserious.github.io

    steps:
      - name: Deploy to GitHub Pages
        # ← 이 부분도 v1 → v4 로 올립니다.
        uses: actions/deploy-pages@v4
